fix: correct invalid import
[This commit] introduced the following runtime error

```
Error: Cannot find module '../src/util.cjs'
```

The offending compiled code looks like

```javascript
var util = _interopRequireWildcard(require("../src/util.cjs"));
```

which does not error when changed to

```javascript
var util = _interopRequireWildcard(require("./util.cjs"));
```

This commit changes the JavaScript source to produce the desired
compiled output.

[this commit]: https://github.com/hashgraph/hedera-sdk-js/pull/709

Closes #729

Signed-off-by: Patrick McLaughlin <patrickmclaughlin@bitgo.com>